[package]
name = "libdafs"
description = "Library for Doug's Advanced File System"
version = "0.1.0"
authors = ["Doug Rezabek <drezabek@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
